# Grafana configuration - simplified to prevent crashes
grafana:
  enabled: true
  adminPassword: admin123
  
  service:
    type: LoadBalancer
    port: 80
  
  # Disable persistence to avoid PVC issues
  persistence:
    enabled: false
  
  # Disable problematic sidecars
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  
  # Add datasource directly in config
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://monitor-kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true
  
  # Minimal resource requirements
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Prometheus configuration
prometheus:
  enabled: true
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    
    # Allow scraping all ServiceMonitors regardless of labels
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

# Disable Alertmanager (not needed for demo)
alertmanager:
  enabled: false

# Keep these components
kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Disable all default alerting rules (reduces complexity)
defaultRules:
  create: false