apiVersion: v1
kind: Service
metadata:
  name: backend-blue-metrics
  namespace: staging
  labels:
    app: backend
    color: blue
spec:
  selector:
    app: backend
    color: blue
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-green-metrics
  namespace: staging
  labels:
    app: backend
    color: green
spec:
  selector:
    app: backend
    color: green
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP