apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: staging
spec:
  selector:
    app: backend
    color: blue
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: prod
spec:
  selector:
    app: backend
    color: blue
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
