# --- STAGING PV (cluster-scoped; no namespace) ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv-staging
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: file.csi.azure.com
    volumeHandle: azurefile-vol-staging
    volumeAttributes:
      shareName: newsflow-staging
    nodeStageSecretRef:
      name: azure-storage-secret
      namespace: staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-pvc
  namespace: staging
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: azurefile-pv-staging

# --- PROD PV (cluster-scoped; no namespace) ---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv-prod
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: file.csi.azure.com
    volumeHandle: azurefile-vol-prod
    volumeAttributes:
      shareName: newsflow-prod
    nodeStageSecretRef:
      name: azure-storage-secret
      namespace: prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-pvc
  namespace: prod
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: azurefile-pv-prod