name: Monitoring - kube-prometheus-stack

on:
  push:
    branches: ["testing", "main"]
  workflow_dispatch: {}

jobs:
  setup_monitoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        shell: bash
        env:
          AKS_KUBECONFIG_B64: ${{ secrets.AKS_KUBECONFIG }}
        run: |
          python - <<'PY'
          import os, base64, re, sys
          b64 = os.environ.get('AKS_KUBECONFIG_B64','')
          if not b64:
            sys.stderr.write("AKS_KUBECONFIG_B64 is empty\n")
            sys.exit(1)
          b64 = re.sub(r'\s+', '', b64).replace('\r','')
          try:
            data = base64.b64decode(b64, validate=True)
          except Exception as e:
            sys.stderr.write(f"Invalid base64 for kubeconfig: {e}\n")
            sys.exit(1)
          open('kubeconfig','wb').write(data)
          PY
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV
          kubectl version --client

      - name: Check if monitoring already installed
        id: check_monitoring
        run: |
          if helm list -n monitoring 2>/dev/null | grep -q monitor; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Monitoring stack already installed, skipping installation"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Monitoring stack not found, will install"
          fi

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add repos
        if: steps.check_monitoring.outputs.exists == 'false'
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Create monitoring namespace
        run: kubectl create ns monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: Install kube-prometheus-stack
        if: steps.check_monitoring.outputs.exists == 'false'
        run: |
          helm upgrade --install monitor prometheus-community/kube-prometheus-stack \
            -n monitoring \
            -f k8s/prometheus/values-kube-prom.yaml \
            --timeout 15m

      - name: Wait for operator and CRDs
        run: |
          echo "Waiting for Prometheus Operator..."
          kubectl -n monitoring wait --for=condition=available deployment -l app.kubernetes.io/name=kube-prometheus-stack-operator --timeout=600s || echo "Operator timeout, checking manually..."
          
          echo "Checking CRDs..."
          for i in {1..30}; do
            if kubectl get crd servicemonitors.monitoring.coreos.com 2>/dev/null; then
              echo "CRDs are ready"
              break
            fi
            echo "Waiting for CRDs... $i/30"
            sleep 10
          done
          
          echo "All pods in monitoring namespace:"
          kubectl -n monitoring get pods

      - name: Wait for Grafana
        run: |
          echo "Waiting for Grafana..."
          for i in {1..60}; do
            READY=$(kubectl -n monitoring get pods -l app.kubernetes.io/name=grafana -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")
            if [[ "$READY" == *"True"* ]]; then
              echo "Grafana is ready"
              break
            fi
            echo "Waiting for Grafana pods... $i/60"
            kubectl -n monitoring get pods -l app.kubernetes.io/name=grafana || true
            sleep 10
          done

      - name: Wait for Prometheus
        run: |
          echo "Waiting for Prometheus..."
          for i in {1..60}; do
            READY=$(kubectl -n monitoring get pods -l app.kubernetes.io/name=prometheus -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")
            if [[ "$READY" == *"True"* ]]; then
              echo "Prometheus is ready"
              break
            fi
            echo "Waiting for Prometheus pods... $i/60"
            kubectl -n monitoring get pods -l app.kubernetes.io/name=prometheus || true
            sleep 10
          done

      - name: Show all monitoring resources
        run: |
          echo "=== All Deployments ==="
          kubectl -n monitoring get deployments
          echo ""
          echo "=== All StatefulSets ==="
          kubectl -n monitoring get statefulsets
          echo ""
          echo "=== All Pods ==="
          kubectl -n monitoring get pods -o wide
          echo ""
          echo "=== All Services ==="
          kubectl -n monitoring get svc

      - name: Apply metrics Service + ServiceMonitors
        run: |
          echo "Applying backend metrics services..."
          kubectl apply -f k8s/metrics/backend-metrics-service.yaml
          
          echo "Applying ServiceMonitors..."
          kubectl apply -f k8s/prometheus/backend-servicemonitor-staging.yaml
          kubectl apply -f k8s/prometheus/backend-servicemonitor-prod.yaml

      - name: Verify ServiceMonitors
        run: |
          sleep 15
          echo "=== ServiceMonitors in staging ==="
          kubectl -n staging get servicemonitor -o wide || echo "None found"
          echo ""
          echo "=== ServiceMonitors in prod ==="
          kubectl -n prod get servicemonitor -o wide || echo "None found"

      - name: Get Grafana access info
        run: |
          echo "Waiting for Grafana LoadBalancer..."
          for i in {1..40}; do
            IP=$(kubectl -n monitoring get svc monitor-grafana -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
            HN=$(kubectl -n monitoring get svc monitor-grafana -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)
            if [ -n "$IP" ] || [ -n "$HN" ]; then
              echo "=========================================="
              echo "GRAFANA ACCESS"
              echo "=========================================="
              echo "URL: http://$IP$HN"
              echo "Username: admin"
              echo "Password: admin123"
              echo "=========================================="
              echo ""
              echo "PROMETHEUS ACCESS (port-forward):"
              echo "kubectl -n monitoring port-forward svc/monitor-kube-prometheus-prometheus 9090:9090"
              echo ""
              echo "EXAMPLE QUERIES:"
              echo "  sum(rate(http_requests_total[5m])) by (color)"
              echo "  active_connections{color=\"blue\"}"
              echo "  active_connections{color=\"green\"}"
              echo "  rate(news_api_calls_total[5m])"
              echo "=========================================="
              exit 0
            fi
            echo "Attempt $i/40..."
            sleep 10
          done
          echo "LoadBalancer pending, check with: kubectl -n monitoring get svc monitor-grafana"