name: Monitoring - kube-prometheus-stack

on:
  push:
    branches: ["testing", "main"]
  workflow_dispatch: {}

jobs:
  setup_monitoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        shell: bash
        env:
          AKS_KUBECONFIG_B64: ${{ secrets.AKS_KUBECONFIG }}
        run: |
          python - <<'PY'
          import os, base64, re, sys
          b64 = os.environ.get('AKS_KUBECONFIG_B64','')
          if not b64:
            sys.stderr.write("AKS_KUBECONFIG_B64 is empty\n")
            sys.exit(1)
          b64 = re.sub(r'\s+', '', b64).replace('\r','')
          try:
            data = base64.b64decode(b64, validate=True)
          except Exception as e:
            sys.stderr.write(f"Invalid base64 for kubeconfig: {e}\n")
            sys.exit(1)
          open('kubeconfig','wb').write(data)
          PY
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV
          kubectl version --client

      - name: Check if monitoring already installed
        id: check_monitoring
        run: |
          if helm list -n monitoring 2>/dev/null | grep -q monitor; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✅ Monitoring stack already installed, skipping installation"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "📦 Monitoring stack not found, will install"
          fi

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add repos
        if: steps.check_monitoring.outputs.exists == 'false'
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Create monitoring namespace
        run: kubectl create ns monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: Install kube-prometheus-stack (without wait)
        if: steps.check_monitoring.outputs.exists == 'false'
        run: |
          helm upgrade --install monitor prometheus-community/kube-prometheus-stack \
            -n monitoring \
            -f k8s/prometheus/values-kube-prom.yaml \
            --timeout 15m \
            --debug

      - name: Wait for CRDs to be ready
        if: steps.check_monitoring.outputs.exists == 'false'
        run: |
          echo "Waiting for Prometheus CRDs..."
          for i in {1..30}; do
            if kubectl get crd servicemonitors.monitoring.coreos.com 2>/dev/null; then
              echo "✅ CRDs are ready"
              break
            fi
            echo "Waiting for CRDs... attempt $i/30"
            sleep 10
          done

      - name: Wait for Prometheus Operator
        run: |
          echo "Waiting for Prometheus Operator deployment..."
          kubectl -n monitoring wait --for=condition=available deployment/monitor-kube-prometheus-operator --timeout=600s || true
          kubectl -n monitoring get pods -l app.kubernetes.io/name=prometheus-operator

      - name: Wait for Grafana
        run: |
          echo "Waiting for Grafana deployment..."
          kubectl -n monitoring wait --for=condition=available deployment/monitor-grafana --timeout=600s || true
          kubectl -n monitoring get pods -l app.kubernetes.io/name=grafana

      - name: Wait for Prometheus pods
        run: |
          echo "Waiting for Prometheus statefulset..."
          for i in {1..60}; do
            READY=$(kubectl -n monitoring get statefulset -l app.kubernetes.io/name=prometheus -o jsonpath='{.items[0].status.readyReplicas}' 2>/dev/null || echo "0")
            if [ "$READY" -gt 0 ]; then
              echo "✅ Prometheus is ready"
              break
            fi
            echo "Waiting for Prometheus... attempt $i/60"
            sleep 10
          done
          kubectl -n monitoring get pods -l app.kubernetes.io/name=prometheus

      - name: Apply metrics Service + ServiceMonitors
        run: |
          kubectl apply -f k8s/metrics/backend-metrics-service.yaml
          kubectl apply -f k8s/prometheus/backend-servicemonitor-staging.yaml
          kubectl apply -f k8s/prometheus/backend-servicemonitor-prod.yaml

      - name: Verify ServiceMonitors
        run: |
          sleep 10
          echo "=== ServiceMonitors in staging ==="
          kubectl -n staging get servicemonitor || echo "None found"
          echo ""
          echo "=== ServiceMonitors in prod ==="
          kubectl -n prod get servicemonitor || echo "None found"
          echo ""
          echo "=== All monitoring pods ==="
          kubectl -n monitoring get pods -o wide

      - name: Show Grafana access info
        run: |
          echo "=== Getting Grafana LoadBalancer IP ==="
          for i in {1..30}; do
            IP=$(kubectl -n monitoring get svc monitor-grafana -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
            HN=$(kubectl -n monitoring get svc monitor-grafana -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)
            if [ -n "$IP" ] || [ -n "$HN" ]; then
              echo "=========================================="
              echo "✅ GRAFANA IS READY!"
              echo "=========================================="
              echo "URL: http://$IP$HN"
              echo "Username: admin"
              echo "Password: admin123"
              echo "=========================================="
              echo ""
              echo "📊 PROMETHEUS ACCESS:"
              echo "kubectl -n monitoring port-forward svc/monitor-kube-prometheus-prometheus 9090:9090"
              echo "Then visit: http://localhost:9090"
              echo ""
              echo "📈 USEFUL QUERIES:"
              echo "  sum(rate(http_requests_total[5m])) by (color)"
              echo "  active_connections"
              echo "  rate(news_api_calls_total[5m])"
              echo ""
              echo "🎨 GRAFANA DASHBOARDS TO IMPORT:"
              echo "  - Kubernetes Pods (ID: 6417)"
              echo "  - Node Exporter (ID: 1860)"
              echo "=========================================="
              exit 0
            fi
            echo "Waiting for LoadBalancer IP... $i/30"
            sleep 10
          done
          echo "⚠️  LoadBalancer IP not yet assigned, but service is running:"
          kubectl -n monitoring get svc monitor-grafana -o wide